### ISSUE TITLE
Is Package v2.2.1.2 Compatible with ES 1.x

### ISSUE THREAD

**Issue by miridfd** [couchbaselabs/elasticsearch-transport-couchbase#114]
I'd like to know if anyone verified whether the package 2.2.1.x is compatible with older version of elasticsearch (1.x).

Thanks,
Miri

**Comment by WillGardella** [comment]
No, and there is no plan to do that.  Because of the changes in the Elasticsearch plugin architecture, we have to build a version of the  Elasticsearch Transport Plugin for each release of Elasticsearch 2.x and above.  

Please consult the version compatibility matrix in the README.md (https://github.com/couchbaselabs/elasticsearch-transport-couchbase) to make sure you're getting the right one.

**Comment by miridfd** [comment]
bummer...

Thanks.
