### ISSUE TITLE
Custom mapping with couchbase elasticsearch transport plugin

### ISSUE THREAD

**Issue by MalhotraKaran** [couchbaselabs/elasticsearch-transport-couchbase#122]
I recently started using couchbase-elasticsearch combo to store and search for documents.

I just came across a scenario where I am required to search a document by email and hence use either "index": "not_analyzed" or "uax_url_email" in the document mapping. But as soon as data from couchbase is replicated to elasticsearch, custom mapping is excluded from "doc" part, causing custom mapping to be ignored.

My issue is similar to https://github.com/couchbaselabs/elasticsearch-transport-couchbase/issues/56, please suggest a suitable fix for the same.

**Comment by Branor** [comment]
Could you provide some more details about the process? What are the steps that you're performing?

In general, you can customize the template that comes with the plugin to include any custom mappings for fields of the doc and then apply the template (HTTP PUT) to override the old one. It might also be a good idea to restrict the template to the indexes you know you'll be replicating to (by prefix), rather than *.
