### ISSUE TITLE
One Type Replication Failure Blocks Other Types Replications 

### ISSUE THREAD

**Issue by miridfd** [couchbaselabs/elasticsearch-transport-couchbase#163]
Hi,

We have a bucket replication, which consists of 5 different entity types.
One entity type has started to have mapping problems because of fields changes.
The other types could not be further replicated, until the problematic type has been filtered out.

Is this behavior reasonable? I'd expect the rest of the valid entity types to continue to be replicated.

Couchbase version: 4.5.1-2844 Enterprise Edition
Elasticsearch version: 2.4.4
Transport Couchbase Plugin version: 2.4.4

Thanks,
Miri

**Comment by Branor** [comment]
Hi Miri,

What you're describing happens because of the way XDCR in Couchbase handles replication failures - it continues to retry forever, which indeed blocks other documents in the same vBucket (shard) from replicating. 
You can solve the problem by setting the couchbase.ignoreFailures config setting to true in the ES config file - this will cause the plugin to only log exceptions to the ES log, but not propagate them back to Couchbase. Obviously, this comes with the drawback that you will no longer see XDCR errors on the Couchbase side, but only in the elastic log.

I'm planning to add a more selective way of ignoring exceptions in the next release. For example, only ignoring mapping errors, but propagating the rest back to Couchbase.

**Comment by miridfd** [comment]
10x for the explanation
