### ISSUE TITLE
Managing Elasticsearch types

### ISSUE THREAD

**Issue by dadoonet** [couchbaselabs/elasticsearch-transport-couchbase#6]
Heya,

One of the best practices you guys are encouraging is to [set ids for documents](http://www.couchbase.com/docs/couchbase-devguide-2.0/keys-documents.html) on the form: `type_id` where `type` sounds like elasticsearch `type`, `_` is a separator and `id` is the real document ID.

So, let's imagine that user that want to manage types in Elasticsearch has followed your best practices. It could be not so complicated to add to couchbase transport plugin one new option `couchbase.typeSeparator`.

Then, if `couchbase.defaultDocumentType` is set to empty, you can send the document to the right type using this separator to split type and id.

What do you think?

**Comment by synhershko** [comment]
Thanks for this. However this requires a full cluster restart on the ES part, I've opened https://github.com/couchbaselabs/elasticsearch-transport-couchbase/issues/63 and will be happy if you could address that

**Comment by shivangshah** [comment]
I have been playing around with this plugin for couple of days now and I have come across a problem (maybe design problem or plugin problem or both) which I cannot figure out. Can anyone help me handle my use case of multi tenancy (would also like to mention the comment I made in the post) ? The question is posted here: 

http://stackoverflow.com/questions/28314272/couchbase-elastic-search-plugin-with-multi-tenancy/28322772#28322772
and here's the description: 
This is more of a design question while integrating couchbase with elastic search plugin. I have used couchbase with multitenancy in our previous product and we followed the the very first suggestion we found on couchbase blog here Single Couchbase Bucket for All Tenants.

Now we are researching on exploiting elastic search features on couchbase data using the couchbase elastic search plugin. Going through the couchbase elastic search plugin documentation (installing and setup) I realized that you will be able to map only one couchbase bucket to one elasticsearch index. That documentation can be found here Elasticsearch plugin configuration and here Connecting to Cluster. Now in that case, just as couchbase bucket, all the documents (regardless of the tenant) will reside in the same index.

Now here's my question. Regardless of how the documents are stored in couchbase, I would like elasticsearch to index to be per tenant. I am still quite new to playing around with the integration between these 2 systems but I am assuming that having separate search index per tenant (and each tenant/index having many different types of it's own) can most definitely 1) increase search performance per tenant 2) the performance of a particular search query on a specific tenant that might have minimal sets of data will not be impacted by having huge sets of data for some other tenant on the same index (although not plausible, assuming that the data sets between tenants differ by a factor of 50x)

What I am wondering is, are my concerns valid. Will performance on search queries be impacted by having all the tenants indexed together? And if so, anyone has any solutions on how can achieve this using couchbase elastic search plugin ?

**Comment by Branor** [comment]
The plugin doesn't allow replicating a bucket to more than one index right now. In theory, it's possible to add, but it would be a very complicated and fragile feature, because could easily end up with the same document in multiple indexes just by changing some configurations. 
HOWEVER! You don't necessarily have to send different tenants to different indexes. You can use the existing feature of mapping documents to types, together with custom routing to ensure that all documents from a single tenant end up under a specific type, and are routed to their own shard. That way you can specify the routing data in the query for improved performance, because ES will only query that particular shard.

You can try a preview build of the new version that includes all these features here: https://github.com/Branor/elasticsearch-transport-couchbase/releases/tag/v2.1.0-SNAPSHOT

PS. You could also try using index aliases with custom filtering and routing to separate tenants without any intervention in the plugin: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-aliases.html
