### ISSUE TITLE
Use with Couchbase 4.0

### ISSUE THREAD

**Issue by mikenorgate** [couchbaselabs/elasticsearch-transport-couchbase#85]
I am trying to use the plugin as part of my testing of Couchbase 4.0 and am getting "Failed to get bucket" on replication

ElasticSearch version: 1.5.2
Couchbase version: 4.0.0-1869 Enterprise Edition (build-1869)

This is the output from http://localhost:9091/pools/default/buckets

>[{"bucketCapabilities":["couchapi"],"saslPassword":"","bucketType":"membase","nodes":[{"ports":{"direct":9091},"couchApiBase":"http://192.168.0.2:9091/default","hostname":"192.168.0.2:9091"}],"name":"default","vBucketServerMap":{"serverList":["192.168.0.2:9091"],"vBucketMap":...},"uuid":"19314f3576f3466d8db560e0534c0052","uri":"/pools/default/buckets/default?bucket_uuid=19314f3576f3466d8db560e0534c0052"}]

**Comment by veacks** [comment]
Same issue for me with Couchbase Version 4 beta 1 for OSX
"Failed to get bucket" 
I have tried also tried to remove the plugin version 2.1.1 but it does not work.
Rolled back to Couchbase 3 and replication work

**Comment by brunoriscado** [comment]
The error seems to occur because, when you kick off replication on the admin XDCR, the request to http://localhost:9091/pools/ seems to be failing with a 401 (so I'm assuming the basic auth is not being sent in the headers correctly)... and therefore it doesn't seem to be able to retrieve the index/bucket information.

**Comment by sbuerk** [comment]
Have the same issue with Couchbase 4.0 Beta and the transport plugin ... is there any way to get this working on 4.0 ?

**Comment by brunoriscado** [comment]
Looking at it very quickly, there doesn't seem to be a world of difference between the 3.x rest api and the 4.0, however the error I pointed out above, seems to be related with a basic auth request to the pools data from the couchbase admin console.

Regardless, I do not believe you'll be seeing the elasticsearch plugin development being resumed, as couchbase developers seem to be working on a Full text search engine for future versions, but I could be wrong:

https://github.com/couchbaselabs/cbft

**Comment by WillGardella** [comment]
This issue is scheduled to be fixed in the GA release of Couchbase Server 4.0. 

On Bruno's other point: Couchbase Server Full Text Search AKA cbft (developer preview) introduces a new feature to Couchbase Server, but it is not a replacement for the Elasticsearch Plugin, which is still under active development.
