### ISSUE TITLE
Can't specify parent if no parent field has been configured

### ISSUE THREAD

**Issue by DanielAntonini** [couchbaselabs/elasticsearch-transport-couchbase#92]
Hi guys,

I have a problem with this:

[2015-08-05 17:27:16,299][WARN ][org.eclipse.jetty.servlet.ServletHandler] /qrs%2f651/_bulk_docs
org.elasticsearch.ElasticsearchIllegalArgumentException: Can't specify parent if no parent field has been configured
    at org.elasticsearch.action.index.IndexRequest.process(IndexRequest.java:636)
    at org.elasticsearch.action.bulk.TransportBulkAction.executeBulk(TransportBulkAction.java:236)
    at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:162)
    at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:67)

And my config file is:

couchbase.maxConcurrentRequests: 1024
couchbase.password : ......
couchbase.username : Administrator
couchbase.typeSelector.documentTypeDelimiter : "::"
couchbase.parentSelector.documentTypeParentFields.hijo : doc.papaid
couchbase.parentSelector : org.elasticsearch.transport.couchbase.capi.DefaultParentSelector
couchbase.typeSelector : org.elasticsearch.transport.couchbase.capi.DelimiterTypeSelector

I saw this configuration: 
http://docs.couchbase.com/connectors/elastic/adv-usage.html

It dont working too.

Regards

**Comment by dnault** [comment]
Hi Daniel,

First off, sorry for the long overdue response.

In order to use parent/child relationships, it's necessary to provide Elasticsearch with a custom mapping for the child document type. This custom mapping must define a `_parent` field that tells ES the type of the parent document.

Here's a curl command you might use to install the type mapping (replace MY_INDEX, MY_CHILD_TYPE, and MY_PARENT_TYPE with your values):

```
curl -XPUT http://localhost:9200/MY_INDEX/_mapping/MY_CHILD_TYPE -d '
{
  "_source": {
    "includes": [
      "meta.*"
    ]
  },
  "_parent": {
    "type": "MY_PARENT_TYPE"
  },
  "properties": {
    "meta": {
      "type": "object",
      "include_in_all": false
    }
  }
}
'
```

This sample mapping is a copy & paste of the `_default_` mapping defined in `couchbase-template.json`), with an added `_parent` field.

I'll see what we can do about providing more documentation for this feature.

Thanks,
David

**Comment by RRSR** [comment]
Still there is no documentation of the same on the official site. [https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-parent-child.html](https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-parent-child.html)

It will greatly help the beginners if the same is documented there.
